// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx4ZE3Qjsxzow_jMWcLtvkl_UEkZXQJHs',
    appId: '1:918142675573:web:6fbf281f0e3731adf7e63c',
    messagingSenderId: '918142675573',
    projectId: 'almoraapp',
    authDomain: 'almoraapp.firebaseapp.com',
    storageBucket: 'almoraapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKnt3gU93LNmEsLFxdGMLV3GG7twufJ2A',
    appId: '1:918142675573:android:38a2f2124c60ae62f7e63c',
    messagingSenderId: '918142675573',
    projectId: 'almoraapp',
    storageBucket: 'almoraapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLUVuyvsVDy7hn9VvvFxIrhm2J2zroWZE',
    appId: '1:918142675573:ios:8521debd4d98994ff7e63c',
    messagingSenderId: '918142675573',
    projectId: 'almoraapp',
    storageBucket: 'almoraapp.appspot.com',
    iosBundleId: 'com.example.almoraPedidos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx4ZE3Qjsxzow_jMWcLtvkl_UEkZXQJHs',
    appId: '1:918142675573:web:823a1762003c227cf7e63c',
    messagingSenderId: '918142675573',
    projectId: 'almoraapp',
    authDomain: 'almoraapp.firebaseapp.com',
    storageBucket: 'almoraapp.appspot.com',
  );
}
